### ISSUE TITLE
Cloudflare Pages Building Failed 

### ISSUE THREAD

**Issue by bishopfunc** [iGEM-Waseda/igemwaseda_hp#20]
![image](https://user-images.githubusercontent.com/61902652/227531746-76233cbe-62b5-48ac-9207-a5f7a89c1a29.png)

毎回Cloudflare Pages のビルドチェックが失敗していて気になる
特に影響はないけど、Cloudflare Pagesは使ってないのでこのチェック項目を削除したい

**Comment by mirito333** [comment]
これがくっついてるcloudflareのアカウントをみたいです

**Comment by bishopfunc** [comment]
cloudflareのアカウント見直したらこのレポジトリが登録された
昔試したことあるのを忘れてた

対応
cloudflare pagesからレポジトリを削除
